amd-apml : update the set-apml.sh script to support new i3c driver
updated the i3c device paths for i3c4, and i3c5 as per the new i3c
driver sysfs design.

Signed-off-by: Mahesh Kurapati <mahesh.kurapati@amd.com>
Change-Id: I8a3142ad6b8068e19213ca2cad7b8547c14b5424

diff --git a/meta-amd/meta-common/recipes-amd/amd-apml/files/0001-amd-apml-Enable-apml-library-with-i3c.patch b/meta-amd/meta-common/recipes-amd/amd-apml/files/0001-amd-apml-Enable-apml-library-with-i3c.patch
--- a/meta-amd/meta-common/recipes-amd/amd-apml/files/0001-amd-apml-Enable-apml-library-with-i3c.patch
+++ b/meta-amd/meta-common/recipes-amd/amd-apml/files/0001-amd-apml-Enable-apml-library-with-i3c.patch
@@ -1,7 +1,7 @@
-From 5d032455b5eef5293d67fa7013d8518baa0cf1b3 Mon Sep 17 00:00:00 2001
+From 4c171e30f27594cf04c2841dd5a7e37bf2a23b31 Mon Sep 17 00:00:00 2001
 From: Supreeth Venkatesh <supreeth.venkatesh@amd.com>
 Date: Tue, 10 May 2022 12:25:40 -0500
-Subject: [PATCH 1/1] amd-apml: Enable apml library with i3c
+Subject: [PATCH] amd-apml: Enable apml library with i3c
 
 Enables apml oob library with i3c.
 Copy of UAPI header file is copied to esmi_oob include folder to resolve
@@ -16,13 +16,14 @@ Require num_of_cpu from u-boot env
 
 Signed-off-by: Supreeth Venkatesh <supreeth.venkatesh@amd.com>
 Signed-off-by: Mohsen Dolaty <mohsen.dolaty@amd.com>
+Signed-off-by: Mahesh Kurapati <mahesh.kurapati@amd.com>
 ---
- include/esmi_oob/amd-apml.h |  74 +++++++++++++
+ include/esmi_oob/amd-apml.h |  74 ++++++++++++
  include/esmi_oob/apml.h     |   2 +-
- scripts/set-apml.sh         | 212 ++++++++++++++++++++++++++++++++++++
- 3 files changed, 287 insertions(+), 1 deletion(-)
+ scripts/set-apml.sh         | 218 ++++++++++++++++++++++++++++++++++++
+ 3 files changed, 293 insertions(+), 1 deletion(-)
  create mode 100644 include/esmi_oob/amd-apml.h
- create mode 100644 scripts/set-apml.sh
+ create mode 100755 scripts/set-apml.sh
 
 diff --git a/include/esmi_oob/amd-apml.h b/include/esmi_oob/amd-apml.h
 new file mode 100644
@@ -105,10 +106,10 @@ index 0000000..cb8f6b2
 +
 +#endif /*_AMD_APML_H_*/
 diff --git a/include/esmi_oob/apml.h b/include/esmi_oob/apml.h
-index c9154d7..f3f1a0c 100644
+index 98bb454..1906e29 100644
 --- a/include/esmi_oob/apml.h
 +++ b/include/esmi_oob/apml.h
-@@ -44,7 +44,7 @@
+@@ -7,7 +7,7 @@
 
  #include <stdbool.h>
 
@@ -118,11 +119,11 @@ index c9154d7..f3f1a0c 100644
 
  /** \file apml.h
 diff --git a/scripts/set-apml.sh b/scripts/set-apml.sh
-new file mode 100644
-index 0000000..5c9d7d9
+new file mode 100755
+index 0000000..8905bd9
 --- /dev/null
 +++ b/scripts/set-apml.sh
-@@ -0,0 +1,212 @@
+@@ -0,0 +1,218 @@
 +#!/bin/bash
 +
 +num_of_cpu=`/sbin/fw_printenv -n num_of_cpu`
@@ -134,20 +135,19 @@ index 0000000..5c9d7d9
 +I2C_MUX=0x70
 +
 +DEV_I2C_SBTSI_PATH="/sys/bus/i2c/drivers/sbtsi"
-+DEV_I2C_SBTSI_2="4-22400000001"
-+DEV_I2C_SBTSI_2="5-22400000001"
-+
++DEV_I2C_SBTSI_2="2-004c"
++DEV_I2C_SBTSI_3="3-0048"
 +DEV_I2C_SBRMI_PATH="/sys/bus/i2c/drivers/sbrmi"
-+DEV_I2C_SBRMI_3="4-22400000002"
-+DEV_I2C_SBRMI_3="5-22400000002"
++DEV_I2C_SBRMI_2="2-003c"
++DEV_I2C_SBRMI_3="3-0038"
 +
 +# i3c bus
 +I3C_TOOL="/usr/bin/i3ctransfer"
-+DEV_I3C_PATH="/sys/bus/platform/drivers/dw-i3c-master"
++DEV_I3C_PATH="/sys/bus/platform/drivers/ast2600-i3c-master"
 +DEV_I3C_4="1e7a6000.i3c4"
 +DEV_I3C_5="1e7a7000.i3c5"
-+I3C_MUX_0="/dev/i3c-4-4cc00000000"
-+I3C_MUX_1="/dev/i3c-5-4cc00000000"
++I3C_MUX_0="/dev/bus/i3c/4-4cc00000000"
++I3C_MUX_1="/dev/bus/i3c/5-4cc00000000"
 +i3c_mux_present=0
 +
 +DEV_I3C_SBTSI_PATH="/sys/bus/i3c/drivers/sbtsi_i3c"
@@ -162,6 +162,7 @@ index 0000000..5c9d7d9
 +set_i2c_apml()
 +{
 +    echo "Setting I2C-2 Mux for CPU APML "
++    I2C_BUS=2
 +    i2cset -f -y $I2C_BUS $I2C_MUX 0x46 0x01 || retval=$?
 +    if [[ "$retval" -ne 0 ]]; then
 +        echo "Error: Setting I2C Mux Reg 0x46"
@@ -172,8 +173,12 @@ index 0000000..5c9d7d9
 +    fi
 +    i2cset -f -y $I2C_BUS $I2C_MUX 0x41 0x40 || retval=$?
 +    if [[ "$retval" -ne 0 ]]; then
-+        echo "Error: Setting I2C Mux Reg 0x46"
++        echo "Error: Setting I2C Mux Reg 0x41"
 +    fi
++    # bind sbtsi/sbrmi driver
++    echo  $DEV_I2C_SBTSI_2 > $DEV_I2C_SBTSI_PATH/bind
++    echo  $DEV_I2C_SBRMI_2 > $DEV_I2C_SBRMI_PATH/bind
++
 +    if [ -a "$DEV_I2C_3" ]
 +    then
 +        echo "Setting I2C-3 Mux for CPU APML "
@@ -188,7 +193,46 @@ index 0000000..5c9d7d9
 +        fi
 +        i2cset -f -y $I2C_BUS $I2C_MUX 0x41 0x40 || retval=$?
 +        if [[ "$retval" -ne 0 ]]; then
-+            echo "Error: Setting I2C Mux Reg 0x46"
++            echo "Error: Setting I2C Mux Reg 0x41"
++        fi
++        # bind sbtsi/sbrmi driver
++        echo  $DEV_I2C_SBTSI_3 > $DEV_I2C_SBTSI_PATH/bind
++        echo  $DEV_I2C_SBRMI_3 > $DEV_I2C_SBRMI_PATH/bind
++    fi
++}
++
++# unbind i2c drivers
++unbind_i2c_drivers()
++{
++    echo "Unbind i2c-2 SBRMI and SBTSI drivers "
++    I2C_BUS=2
++    # Unbind sbtsi/sbrmi driver
++    echo  $DEV_I2C_SBTSI_2 > $DEV_I2C_SBTSI_PATH/unbind
++    echo  $DEV_I2C_SBRMI_2 > $DEV_I2C_SBRMI_PATH/unbind
++    #disable i2c MUX
++    i2cset -f -y $I2C_BUS $I2C_MUX 0x40 0x00 || retval=$?
++    if [[ "$retval" -ne 0 ]]; then
++        echo "Error: Setting I2C Mux Reg 0x40"
++    fi
++    i2cset -f -y $I2C_BUS $I2C_MUX 0x41 0x00 || retval=$?
++    if [[ "$retval" -ne 0 ]]; then
++        echo "Error: Setting I2C Mux Reg 0x41"
++    fi
++    if [ -a "$DEV_I2C_3" ]
++    then
++        echo "unbind i2c-3 SBRMI and SBTSI drivers"
++        I2C_BUS=3
++        # Unbind sbtsi/sbrmi driver
++        echo  $DEV_I2C_SBTSI_3 > $DEV_I2C_SBTSI_PATH/unbind
++        echo  $DEV_I2C_SBRMI_3 > $DEV_I2C_SBRMI_PATH/unbind
++        #disable i2c MUX
++        i2cset -f -y $I2C_BUS $I2C_MUX 0x40 0x00 || retval=$?
++        if [[ "$retval" -ne 0 ]]; then
++            echo "Error: Setting I2C Mux Reg 0x40"
++        fi
++        i2cset -f -y $I2C_BUS $I2C_MUX 0x41 0x00 || retval=$?
++        if [[ "$retval" -ne 0 ]]; then
++            echo "Error: Setting I2C Mux Reg 0x41"
 +        fi
 +    fi
 +}
@@ -197,33 +241,12 @@ index 0000000..5c9d7d9
 +set_i3c_apml()
 +{
 +    echo "Setting I3C Mux for CPU 0 APML "
-+    if [ -a "$I3C_MUX_0" ]
-+    then
-+        $I3C_TOOL -d $I3C_MUX_0 -w 0x46 -r 1 > /dev/null 2>&1
-+        if [[ $? -ne 0 ]]
-+        then
-+            echo "I3C Mux 0 not present"
-+            i3c_mux_present=0
-+        else
-+            echo "I3C Mux 0 present"
-+            i3c_mux_present=0
-+        fi
-+    else
-+        i3c_mux_present=0
-+    fi
-+    if [[ $i3c_mux_present == 0 ]]
-+    then
-+        # Unbind sbtsi driver
-+        echo  $DEV_I3C_SBTSI_4 > $DEV_I3C_SBTSI_PATH/unbind
-+        echo  $DEV_I3C_SBRMI_4 > $DEV_I3C_SBRMI_PATH/unbind
-+        sleep 1
-+        # Unbind platform i3c driver
-+        echo  $DEV_I3C_4 > $DEV_I3C_PATH/unbind
-+        sleep 1
-+        # Bind platform i3c driver
-+        echo  $DEV_I3C_4 > $DEV_I3C_PATH/bind
-+        sleep 1
-+    fi
++
++    sleep 1
++    # Bind platform i3c driver
++    echo  $DEV_I3C_4 > $DEV_I3C_PATH/bind
++    sleep 1
++
 +    $I3C_TOOL -d $I3C_MUX_0 -w 0x46,0x00,0x01
 +    $I3C_TOOL -d $I3C_MUX_0 -w 0x0E,0x00,0x24
 +    $I3C_TOOL -d $I3C_MUX_0 -w 0x40,0x00,0x40
@@ -241,34 +264,11 @@ index 0000000..5c9d7d9
 +
 +    if [[ $num_of_cpu == 2 ]]
 +    then
-+        echo "Setting I3C Mux for CPU 1 APML "
-+        if [ -a "$I3C_MUX_1" ]
-+        then
-+            $I3C_TOOL -d $I3C_MUX_1 -w 0x46 -r 1 > /dev/null 2>&1
-+            if [[ $? -ne 0 ]]
-+            then
-+                echo "I3C Mux 1 not present"
-+                i3c_mux_present=0
-+            else
-+                echo "I3C Mux 1 present"
-+                i3c_mux_present=0
-+            fi
-+        else
-+            i3c_mux_present=0
-+        fi
-+        if [[ $i3c_mux_present == 0 ]]
-+        then
-+            # Unbind sbtsi driver
-+            echo  $DEV_I3C_SBTSI_5 > $DEV_I3C_SBTSI_PATH/unbind
-+            echo  $DEV_I3C_SBRMI_5 > $DEV_I3C_SBRMI_PATH/unbind
-+            sleep 1
-+            # Unbind platform i3c driver
-+            echo  $DEV_I3C_5 > $DEV_I3C_PATH/unbind
-+            sleep 1
-+            # Bind platform i3c driver
-+            echo  $DEV_I3C_5 > $DEV_I3C_PATH/bind
-+            sleep 1
-+        fi
++        sleep 1
++        # Bind platform i3c driver
++        echo  $DEV_I3C_5 > $DEV_I3C_PATH/bind
++        sleep 1
++
 +        $I3C_TOOL -d $I3C_MUX_1 -w 0x46,0x00,0x01
 +        $I3C_TOOL -d $I3C_MUX_1 -w 0x0E,0x00,0x24
 +        $I3C_TOOL -d $I3C_MUX_1 -w 0x40,0x00,0x40
@@ -285,29 +285,23 @@ index 0000000..5c9d7d9
 +    fi
 +}
 +
-+# unbind i2c drivers
-+unbind_i2c_drivers()
-+{
-+    # Unbind sbtsi and sbrmi drivers
-+    echo  $DEV_I2C_SBTSI_2 > $DEV_I2C_SBTSI_PATH/unbind
-+    echo  $DEV_I2C_SBRMI_2 > $DEV_I2C_SBRMI_PATH/unbind
-+    if [[ $num_of_cpu == 2 ]]
-+    then
-+        echo  $DEV_I2C_SBTSI_3 > $DEV_I2C_SBTSI_PATH/unbind
-+        echo  $DEV_I2C_SBRMI_3 > $DEV_I2C_SBRMI_PATH/unbind
-+    fi
-+}
-+
 +# unbind i3c drivers
 +unbind_i3c_drivers()
 +{
 +    # Unbind sbtsi and sbrmi drivers
 +    echo  $DEV_I3C_SBTSI_4 > $DEV_I3C_SBTSI_PATH/unbind
 +    echo  $DEV_I3C_SBRMI_4 > $DEV_I3C_SBRMI_PATH/unbind
++    # Unbind platform i3c driver
++    sleep 1
++    echo  $DEV_I3C_4 > $DEV_I3C_PATH/unbind
++
 +    if [[ $num_of_cpu == 2 ]]
 +    then
 +        echo  $DEV_I3C_SBTSI_5 > $DEV_I3C_SBTSI_PATH/unbind
 +        echo  $DEV_I3C_SBRMI_5 > $DEV_I3C_SBRMI_PATH/unbind
++        # Unbind platform i3c driver
++        sleep 1
++        echo  $DEV_I3C_5 > $DEV_I3C_PATH/unbind
 +    fi
 +}
 +
@@ -317,23 +311,36 @@ index 0000000..5c9d7d9
 +# check num of cpu
 +echo "Num of CPU " $num_of_cpu
 +
-+if [ $1 == "bind" ]
-+then
-+    echo "Bind Drivers"
-+    if [ -a "$DEV_I2C_2" ]
-+    then
++if [[ $1 == "i3c" ]];then
++    fw_setenv apml_i3c true
++    reboot now
++elif [[ $1 == "i2c" ]];then
++    fw_setenv apml_i3c false
++    reboot now
++elif [[ $1 == "bind" ]];then
++    if [[ -a "$DEV_I2C_2" ]];then
++        echo "Bind I2C Drivers"
 +        set_i2c_apml
 +    else
++        echo "Bind I3C Drivers"
 +        set_i3c_apml
 +    fi
-+else
-+    echo "Unbind Drivers"
-+    if [ -a "$DEV_I2C_2" ]
-+    then
++elif [[ $1 == "unbind" ]];then
++    if [[ -a "$DEV_I2C_2" ]];then
++        echo "UnBind I2C Drivers"
 +        unbind_i2c_drivers
 +    else
++        echo "UnBind I3C Drivers"
 +        unbind_i3c_drivers
 +    fi
++else
++    echo "set-apml.sh takes a single string as input"
++    echo "    i3c    = set APML to I3C mode, and Reboot"
++    echo "    i2c    = set APML to I2C mode, and Reboot"
++    echo "    bind   = Bind   I2C/I3C drivers for APML"
++    echo "    unbind = Unbind I2C/I3C drivers for APML"
++    echo "APML mode is"
++    fw_printenv |grep apml_i3c
 +fi
 --
 2.25.1
